# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiv2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(704, 565)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("MBDicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.six_with_radio = QtWidgets.QRadioButton(self.centralwidget)
        self.six_with_radio.setGeometry(QtCore.QRect(47, 119, 110, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.six_with_radio.setFont(font)
        self.six_with_radio.setObjectName("six_with_radio")
        self.nine_with_radio = QtWidgets.QRadioButton(self.centralwidget)
        self.nine_with_radio.setGeometry(QtCore.QRect(190, 119, 110, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nine_with_radio.setFont(font)
        self.nine_with_radio.setObjectName("nine_with_radio")
        self.six_without_radio = QtWidgets.QRadioButton(self.centralwidget)
        self.six_without_radio.setGeometry(QtCore.QRect(47, 160, 137, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.six_without_radio.setFont(font)
        self.six_without_radio.setObjectName("six_without_radio")
        self.nine_without_radio = QtWidgets.QRadioButton(self.centralwidget)
        self.nine_without_radio.setGeometry(QtCore.QRect(190, 160, 137, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nine_without_radio.setFont(font)
        self.nine_without_radio.setObjectName("nine_without_radio")
        self.seconds_label = QtWidgets.QLabel(self.centralwidget)
        self.seconds_label.setGeometry(QtCore.QRect(600, 90, 66, 19))
        self.seconds_label.setObjectName("seconds_label")
        self.intro_sil_check = QtWidgets.QCheckBox(self.centralwidget)
        self.intro_sil_check.setGeometry(QtCore.QRect(610, 180, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.intro_sil_check.setFont(font)
        self.intro_sil_check.setChecked(True)
        self.intro_sil_check.setObjectName("intro_sil_check")
        self.moves_input = QtWidgets.QSpinBox(self.centralwidget)
        self.moves_input.setGeometry(QtCore.QRect(100, 290, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.moves_input.setFont(font)
        self.moves_input.setObjectName("moves_input")
        self.moves_label = QtWidgets.QLabel(self.centralwidget)
        self.moves_label.setGeometry(QtCore.QRect(70, 260, 147, 19))
        self.moves_label.setObjectName("moves_label")
        self.style_choice_widget = QtWidgets.QWidget(self.centralwidget)
        self.style_choice_widget.setGeometry(QtCore.QRect(30, 20, 601, 51))
        self.style_choice_widget.setObjectName("style_choice_widget")
        self.traditional_radio = QtWidgets.QRadioButton(self.style_choice_widget)
        self.traditional_radio.setGeometry(QtCore.QRect(20, 30, 113, 23))
        self.traditional_radio.setObjectName("traditional_radio")
        self.contemporary_radio = QtWidgets.QRadioButton(self.style_choice_widget)
        self.contemporary_radio.setGeometry(QtCore.QRect(160, 30, 139, 23))
        self.contemporary_radio.setObjectName("contemporary_radio")
        self.custom_radio = QtWidgets.QRadioButton(self.style_choice_widget)
        self.custom_radio.setGeometry(QtCore.QRect(450, 30, 151, 21))
        self.custom_radio.setObjectName("custom_radio")
        self.frames_label = QtWidgets.QLabel(self.centralwidget)
        self.frames_label.setGeometry(QtCore.QRect(560, 290, 61, 21))
        self.frames_label.setObjectName("frames_label")
        self.minutes_input = QtWidgets.QSpinBox(self.centralwidget)
        self.minutes_input.setGeometry(QtCore.QRect(400, 90, 47, 25))
        self.minutes_input.setObjectName("minutes_input")
        self.minutes_label = QtWidgets.QLabel(self.centralwidget)
        self.minutes_label.setGeometry(QtCore.QRect(460, 90, 64, 19))
        self.minutes_label.setObjectName("minutes_label")
        self.seconds_input = QtWidgets.QSpinBox(self.centralwidget)
        self.seconds_input.setGeometry(QtCore.QRect(540, 90, 47, 25))
        self.seconds_input.setObjectName("seconds_input")
        self.transition_length_input = QtWidgets.QSpinBox(self.centralwidget)
        self.transition_length_input.setGeometry(QtCore.QRect(540, 160, 51, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.transition_length_input.setFont(font)
        self.transition_length_input.setObjectName("transition_length_input")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(370, 160, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.vertical_break = QtWidgets.QFrame(self.centralwidget)
        self.vertical_break.setGeometry(QtCore.QRect(340, 20, 20, 211))
        self.vertical_break.setFrameShape(QtWidgets.QFrame.VLine)
        self.vertical_break.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vertical_break.setObjectName("vertical_break")
        self.goButton = QtWidgets.QPushButton(self.centralwidget)
        self.goButton.setGeometry(QtCore.QRect(280, 270, 141, 51))
        self.goButton.setObjectName("goButton")
        self.horizontal_break = QtWidgets.QFrame(self.centralwidget)
        self.horizontal_break.setGeometry(QtCore.QRect(20, 240, 671, 16))
        self.horizontal_break.setFrameShape(QtWidgets.QFrame.HLine)
        self.horizontal_break.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontal_break.setObjectName("horizontal_break")
        self.scenery_clips_input = QtWidgets.QSpinBox(self.centralwidget)
        self.scenery_clips_input.setGeometry(QtCore.QRect(540, 200, 51, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.scenery_clips_input.setFont(font)
        self.scenery_clips_input.setObjectName("scenery_clips_input")
        self.scenery_clips_label = QtWidgets.QLabel(self.centralwidget)
        self.scenery_clips_label.setGeometry(QtCore.QRect(370, 200, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.scenery_clips_label.setFont(font)
        self.scenery_clips_label.setObjectName("scenery_clips_label")
        self.frames_output = QtWidgets.QLabel(self.centralwidget)
        self.frames_output.setGeometry(QtCore.QRect(480, 270, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.frames_output.setFont(font)
        self.frames_output.setAutoFillBackground(True)
        self.frames_output.setObjectName("frames_output")
        self.additional_info = QtWidgets.QTextBrowser(self.centralwidget)
        self.additional_info.setGeometry(QtCore.QRect(20, 380, 671, 145))
        self.additional_info.setObjectName("additional_info")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 360, 201, 16))
        self.label.setObjectName("label")
        self.helpButton = QtWidgets.QPushButton(self.centralwidget)
        self.helpButton.setGeometry(QtCore.QRect(610, 350, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.helpButton.setFont(font)
        self.helpButton.setObjectName("helpButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 704, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Timing Program"))
        self.six_with_radio.setText(_translate("MainWindow", "6 Min With"))
        self.nine_with_radio.setText(_translate("MainWindow", "9 Min With"))
        self.six_without_radio.setText(_translate("MainWindow", "6 Min Without"))
        self.nine_without_radio.setText(_translate("MainWindow", "9 Min Without"))
        self.seconds_label.setText(_translate("MainWindow", "Seconds"))
        self.intro_sil_check.setText(_translate("MainWindow", "Intro Sil?"))
        self.moves_label.setText(_translate("MainWindow", "Number of Moves:"))
        self.traditional_radio.setText(_translate("MainWindow", "Traditional"))
        self.contemporary_radio.setText(_translate("MainWindow", "Contemporary"))
        self.custom_radio.setText(_translate("MainWindow", "Custom"))
        self.frames_label.setText(_translate("MainWindow", "Frames"))
        self.minutes_label.setText(_translate("MainWindow", "Minutes"))
        self.label_6.setText(_translate("MainWindow", "Transition Length -->"))
        self.goButton.setText(_translate("MainWindow", "Calculate"))
        self.scenery_clips_label.setText(_translate("MainWindow", "# of scenery clips -->"))
        self.frames_output.setText(_translate("MainWindow", "000"))
        self.label.setText(_translate("MainWindow", "Additional Information:"))
        self.helpButton.setText(_translate("MainWindow", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

